export enum ActionTypes {
    FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST',
    FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
    FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE',
    LOGIN_USER = 'LOGIN_USER',
    LOGOUT_USER= 'LOGOUT_USER'
  }
  